### ISSUE TITLE
Bottom nav is behaving wierdly

### ISSUE THREAD

**Issue by hardiksachan** [lotdrops/Composing-Clocks#1]
Hi,

I am trying to use the nav system you used in this project in one of mine. But I am facing some issues. It'd be great if you could help me out.

I have two subgraphs - Instrument and Transaction, which are also shown on the bottom bar. When I press instruments, it does not navigate to instrument, but starts switching between instrument and transaction. I've attached a screen recording below.

[Here](https://github.com/hardiksachan/Ledger) is a link to project repo

![ezgif com-gif-maker](https://user-images.githubusercontent.com/60518745/148717352-5d6b3c72-53e9-49c6-8896-4fd56b825180.gif)

**Comment by lotdrops** [comment]
I just tested it and it seems to work fine. You already fixed it, right?
